<footer>
    <p>
        Don't dare complaining about this website's design. I'm a programmer (and medic), not a designer ;-)<br>
        If you'd like to improve the design, just submit a pull request on this website's public
        <a href="https://github.com/ShadyMedic/TerminoveTrziste/" target="_blank">GitHub repository</a>.
    </p>
    <p>
        Did my website help you? You can express your gratitude by throwing me a bone. Even a few cents will make my
        day.<br>
        <a href="https://liberapay.com/ShadyMedic/donate">
            <img alt="Donate using Liberapay" src="https://liberapay.com/assets/widgets/donate.svg" class="donate-btn">
        </a>
    </p>
</footer>
</body>
</html>