</main>
<footer>
    <p>
        Did my website help you? You can express your gratitude by throwing me a bone. Even a few cents will make my
        day.<br>
        <a href="https://liberapay.com/ShadyMedic/donate"><img alt="Donate using Liberapay" src="/public/img/liberapay.svg" class="donate-btn"></a>
        <a href="https://github.com/ShadyMedic/TerminoveTrziste"><img alt="Contribute on GitHub" src="/public/img/github.png" class="repo-btn"></a>
    </p>
</footer>
</body>
</html>
