<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Exam Date Marketplace</title>
    <link rel="stylesheet" href="/public/global.css">
</head>
<body>
<section>
    <header>
        <h1>Welcome to Exam Date Marketplace</h1>
    </header>
    <article>
        <p>Is your exam period not going well? Or is studying going faster than expected?</p>
        <p>If any of those is your case, you might want to exchange your reserved exam date for a better fitting one.</p>
        <p>You're welcome to use this service to offer your exam date in exchange for a different one, that you specify.</p>
    </article>
</section>
<section>
    <header>
        <h2>Choose one of the following:</h2>
    </header>
    <article class="flex">
        <a href="/filter.php">
        <div>
            <strong>Browse Adverts</strong>
            <br>
            (please do this first)
        </div>
        </a>
        <a href="/new.php">
        <div>
            <strong>Create Advert</strong>
            <br>
            (quick and easy, I promise)
        </div>
        </a>
    </article>
</section>
<footer>
    <p>
        Don't dare complaining about this website's design. I'm a programmer (and medic), not a designer ;-)<br>
        If you'd like to improve the design, just submit a pull request on this website's public
        <a href="https://github.com/ShadyMedic/TerminoveTrziste/" target="_blank">GitHub repository</a>.
    </p>
</footer>
</body>
</html>