<?php require 'Includes/Head.phtml'; ?>
<section>
    <header>
        <h1>Welcome to Exam Date Marketplace</h1>
    </header>
    <article>
        <p>Is your exam period not going well? Or is studying going faster than expected?</p>
        <p>If any of those is your case, you might want to exchange your reserved exam date for a better fitting one.</p>
        <p>You're welcome to use this service to offer your exam date in exchange for a different one, that you specify.</p>
    </article>
</section>
<section>
    <header>
        <h2>Choose one of the following:</h2>
    </header>
    <article class="flex">
        <a href="/filter.php">
        <div>
            <strong>Browse Adverts</strong>
            <br>
            (please do this first)
        </div>
        </a>
        <a href="/new.php">
        <div>
            <strong>Create Advert</strong>
            <br>
            (quick and easy, I promise)
        </div>
        </a>
    </article>
</section>
<?php require 'Includes/Foot.phtml'; ?>

