<?php require 'Includes/Head.phtml'; ?>
<section>
    <header>
        <h1>Message sent</h1>
    </header>
    <article>
        <p>Your reaction has successfully been sent to the author of this advert.</p>
        <p>This advert has also now been hidden from public view, so other won't be reacting to it now.</p>
        <p>
            Pay close attention to your e-mail inbox, the author of this advert will reply to you if they want
            to proceed with the exchange.
        </p>
        <p>
            <strong>Please, do not react to more adverts concerning the same subject now.</strong>
        </p>
    </article>
</section>
<?php require 'Includes/Foot.phtml'; ?>
