<?php require 'Includes/Head.phtml'; ?>
<section>
    <header>
        <h1>Message couldn't be sent</h1>
    </header>
    <article>
        <p>There was a technical problem with sending your message, it's probably not your fault.</p>
        <p>Please report this at jan.stech@posteo.net.</p>
        <p>I'm sorry for the inconvenience, I'll try to get this fixed as soon as possible.</p>
    </article>
</section>
<?php require 'Includes/Foot.phtml'; ?>
