<?php require 'Includes/Head.phtml'; ?>
<section>
    <header>
        <h1>Exam dates you'd like</h1>
    </header>
    <article>
        <p>
            Below are all future exam dates for your subject that were loaded right from SIS. Pick all that are
            acceptable for you.
        </p>
        <form method="post" action="/advert.php">
            <input type="hidden" name="token" value="<?= $advert->getToken() ?>">
            <fieldset style="column-count: 2; column-gap: 2.5px;">
                <?php foreach ($counteroffers as $counteroffer) : ?>
                    <div>
                        <input type="checkbox" id="counteroffer<?= strtr($counteroffer, " :", "--") ?>"
                               name="counteroffer[]" value="<?= $counteroffer ?>">
                        <label for="counteroffer<?= strtr($counteroffer, " :", "--") ?>">
                            <?= DateTime::createFromFormat('Y-m-d', $counteroffer)->format('l, jS F'); ?>
                        </label>
                    </div>
                <?php endforeach ?>
            </fieldset>
            <fieldset>
                <p>And we're done here! Just one more thing.</p>
                <p>
                    <input type="checkbox" name="sendmail" id="onetime-mail" checked>
                    <label for="onetime-mail">
                        I'm okay with receiving a <strong>one-time e-mail</strong> containing a link through which I can
                        disable or delete this advert anytime later.
                    </label>
                </p>
                <p style="text-align: center;">
                    <input type="submit" value="Publish Advert" style="font-size: 1.5em; font-weight: bold;">
                </p>
            </fieldset>
        </form>
    </article>
</section>
<?php require 'Includes/Foot.phtml'; ?>
